# Generated by Django 5.0 on 2023-12-15 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(unique=True)),
                ('gender', models.CharField(choices=[('', 'Select Gender'), ('M', 'Male'), ('F', 'Female')])),
                ('email', models.CharField(unique=True)),
                ('password', models.CharField()),
            ],
        ),
    ]
